apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: crds-video
  namespace: api
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: crds-video
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2
      maxUnavailable: 0
  template: 
    metadata: 
      labels: 
        app: crds-video
    spec: 
      containers: 
        - name: crds-video
          image: crdschurch/crds-video-service:$DOCKER_TAG 
          imagePullPolicy: Always 
          ports: 
            - containerPort: 80 
          resources: 
            limits: 
              memory: "2Gi"
              cpu: "700m" 
            requests: 
              memory: "16Mi" 
              cpu: "100m" 
          readinessProbe:
            httpGet:
              path: /health/status
              port: 3000
            initialDelaySeconds: 1
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 3
          env:
            - name: CONTENTFUL_SPACE_ID
              value: $CONTENTFUL_SPACE_ID
            - name: CONTENTFUL_ENV
              value: $CONTENTFUL_ENV
            - name: CONTENTFUL_MANAGEMENT_TOKEN
              value: $CONTENTFUL_MANAGEMENT_TOKEN
            - name: CONTENTFUL_ACCESS_TOKEN
              value: $CONTENTFUL_ACCESS_TOKEN
            - name: LOGZIO_API_KEY
              value: $LOGZIO_API_KEY
            - name: CRDS_ENV
              value: $CRDS_ENV
            - name: BITMOVIN_API_KEY
              value: $BITMOVIN_API_KEY
            - name: BITMOVIN_INPUT_ID
              value: $BITMOVIN_INPUT_ID
            - name: BITMOVIN_OUTPUT_ID
              value: $BITMOVIN_OUTPUT_ID
            - name: CLOUDFRONT_DOMAIN
              value: $CLOUDFRONT_DOMAIN
            - name: CLOUD_REGION
              value: $CLOUD_REGION
            - name: INPUT_FILE_HOST
              value: $INPUT_FILE_HOST
            - name: NEW_RELIC_LICENSE_KEY            
              value: $NR_INSTALL_KEY
            - name: NEW_RELIC_APP_NAME
              value: $NR_APP_NAME
            - name: NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
              value: $NEW_RELIC_DISTRIBUTED_TRACING_ENABLED
