apiVersion: v1 
kind: Service 
metadata: 
  name: crds-video-service
  namespace: api
  labels: 
    app: crds-video-service
spec: 
  ports: 
  - name: node
    port: 80
    targetPort: 3000
  selector:
    app: crds-video
