apiVersion: v1 
kind: Service 
metadata: 
  name: crds-search-index-service
  namespace: api
  labels: 
    app: crds-search-index-service
spec: 
  ports: 
  - name: node
    port: 80
    targetPort: 3000
  selector:
    app: crds-search-index