version: '3'
services:
  node:
    image: crdschurch/crds-video-service:${DOCKER_TAG:-local}
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
    container_name: video-service
    ports:
      - 4000:4000
      