version: '3'
services:
  video:
    build:
      context: ../../
      dockerfile: ./deployment/docker/Dockerfile
    container_name: video
    ports:
      - 3000:3000
      - 4000:4000
    env_file: 
      - .env
    volumes:
      - ../../:/usr/src/app
    entrypoint: 
      - ./deployment/docker/entrypoint-local.sh